### PR TITLE
Introduces prompt timeout (-w)

### PR DESCRIPTION
**Pull request by udondan**
I love this script! Also the recent addition (#3) was helpful. For my feeling the pace though was too much. I wanted to create a fully automated demo which requires the user not to press enter, but have a more natural flow.

I added a new option `-w` and the var `PROMPT_TIMEOUT`.

This will wait 1 second at every `pe` and `p`:
```bash
demo.sh -w1
```

In combination with the `-n` option and the `wait` function custom timeouts can be set anywhere in the script:

```bash
PROMPT_TIMEOUT=5
wait
```

### CODE REVIEW

**Comment by kkdk5535** [comment]
@udondan
+1 to add this feature to demo-magic.

**Comment by udondan** [comment]
Here's a recording showing the behavior of the new option with `-w1`

https://groupon.github.io/ansible-silo/

**Comment by paxtonhare** [comment]
@udondan thanks!

Btw, how did you come across this repo?

**Comment by udondan** [comment]
I attended KubeCon earlier this year in Berlin and listened to @janetkuo giving a talk about [Running Workloads in Kubernetes](https://youtu.be/spHPCc82ACs). Starting at [8:17](https://youtu.be/spHPCc82ACs?t=8m17s) she is using something that might be demo-magic. I don't know what she's using but I liked it and was squeezing the hell out of Google to find it and thus came across demo-magic. The search terms that brought me finally here were [shell tool demo](https://www.google.de/search?q=shell+tool+for+demo&oq=shell+tool+demo).

**Comment by paxtonhare** [comment]
@udondan sweet. Thanks for that. I'll tweak the description to make it easier for folks to find.

**Pull request merged**
